Breakpack/#23
CASPER-REPSAC/new-casper-frontend pull request #25
Opened 2023-08-01 07:06 UTC by breakpack

api 연동 시작

2023-08-01 11:26 UTC, jijiseong commented on src/pages/login/register/index.tsx
> +  const onInvalid = (data: any) => {alert("입력값들을 확인해 주세요")};
```suggestion
const onValid: SubmitHandler<LoginFormProps> = (data) => {
    const API = `${API_URL}/api/login`;
    fetch(API, {
      method: 'POST',
      body: data,
      headers: { 'Content-Type': 'application/json' },
    }).then((res) => console.log(res));
  };
  const onInvalid: SubmitErrorHandler<LoginFormProps> = (data) => {
    alert('입력값들을 확인해 주세요');
  };
```

2023-08-01 11:26 UTC, jijiseong commented on src/pages/login/register/index.tsx
> +  const onInvalid = (data: any) => {alert("입력값들을 확인해 주세요")};
nextjs의 `rewrites` 기능 이용해서 `api url`, `api key` 등 숨기기도 가능

fetch 로직들은 api.ts 파일 하나 따로 분리해서 만드는 것도 좋음

2023-08-01 11:26 UTC, jijiseong commented on src/pages/login/register/index.tsx
> +              }
이것도 변수로 따로 분리하는게 가독성이 좋음

2023-08-01 11:26 UTC, jijiseong commented on src/pages/login/register/index.tsx
> +        {errors.id && <InputErrors>{errors.id.message}</InputErrors>}
return 문 안의 js 코드는 최대한 위쪽으로 뺴는게 좋음
예를 들면 아래와 같은 식
```typescript
...
const IdErrorMessage = errors.id && <InputErrors>{errors.id.message}</InputErrors>

return(
...
{IdErrorMessage}
...
)
```

2023-08-08 14:09 UTC, jijiseong commented on src/pages/login/register/index.tsx
> +    }
소문자, camelCase

2023-08-08 14:13 UTC, jijiseong commented on src/pages/login/register/index.tsx
> +const Birthday_Regex = /^[0-9]{4}[0-9]{2}[0-9]{2}$/;
소문자, camelCase

2023-08-19 01:50 UTC, jijiseong requested changes

2023-08-24 00:39 UTC, jijiseong requested changes

2023-08-24 00:39 UTC, jijiseong commented on src/pages/boards/[board_type]/[post_id]/index.tsx
> +        .post('/api/article/boards/' + 'notice_board' + '/' + '0' + '/' + idx)
template literal 이용

\`/api/article/boards/notice_board/0/${idx}`

2023-08-24 00:39 UTC, jijiseong commented on src/pages/boards/[board_type]/[post_id]/index.tsx
> +  const [contentData, SetcontentData] = useState([]);
# **필수**
요청으로 받아온 데이터는 타입 정의 할것, 

```ts
interface contentResponse{
  // api 명세에 맞는 타입 정의
  //  ex) 
  // title: stirng
  // content: string
}
const [contentData, SetcontentData] = useState<contentResponse[]>([]);

```


정확한 코드 아님, 명세에 맞춰서 작성

2023-08-24 00:39 UTC, jijiseong commented on src/pages/boards/[board_type]/new/index.tsx
> +      })
await 썼으면 
then 필요없음

`then` 보다는 `async - await` 를 많이 씀
`then`은 체이닝 되면서 들여쓰기 깊이가 깊어짐

2023-08-24 00:39 UTC, jijiseong commented on src/pages/login/index.tsx
> +      })
얘도 `then` 없애도 됩니다.

들여쓰기는 최대한 없애면 좋음

2023-08-31 09:34 UTC, breakpack commented on src/pages/boards/[board_type]/[post_id]/index.tsx
> +        .post('/api/article/boards/' + 'notice_board' + '/' + '0' + '/' + idx)
이거 테스트용으로 그냥 적은거라 페이지네이션 끝나면 고치겠습니당

2023-09-01 09:34 UTC, jijiseong approved these changes

2023-09-01 09:34 UTC, merged